language: python
addons:
  apt:
    packages:
    - rabbitmq-server 
services:
  - redis-server
  - mongodb
  - rabbitmq-server
install:
  - conda create --yes -n condaenv python=$TRAVIS_PYTHON_VERSION
  - conda install --yes -n condaenv pip
  - source activate condaenv
  - conda install --yes python=$TRAVIS_PYTHON_VERSION numpy scipy
  - pip install --quiet --upgrade pip
  - pip install -r test-requirements.txt
  - pip install .
  - pip install -q $DJANGO
before_script:
  - "export PYTHONPATH=$TRAVIS_BUILD_DIR:$PYTHONPATH;"
  - "django-admin.py version;"
  - "flake8 --exclude=docs,south_migrations,tests,tasks --ignore=E501,E123,E124,E126,E127,E128 --statistics .;"
python:
  - "3.5"
  - "3.6"
  - "3.7"
env:
  - DJANGO="Django>=1.9,<1.10"
  - DJANGO="Django>=1.10,<1.11"
script: python recommends/tests/runtests.py
after_failure:
  - env
  - cat $PYTHONPATH
